/* File generato automaticamente da items.lua e weapons.lua.
   Per rigenerarlo, ripetere il parsing sui file .lua originali. */

const INVENTARIO_ITEMS = [
  { id: 'bandage', label: 'Benda', image: 'bandage.png' },
  { id: 'parachute', label: 'Paracadute', image: 'parachute.png' },
  { id: 'armour', label: 'Giubotto antiproiettile', image: 'armour.png' },
  { id: 'money', label: 'Contanti', image: 'money.png' },
  { id: 'black_money', label: 'Soldi sporchi', image: 'black_money.png' },
  { id: 'patente', label: 'Patente', image: 'patente.png' },
  { id: 'patentea', label: 'Patente A', image: 'patentea.png' },
  { id: 'patentec', label: 'Patente C', image: 'patentec.png' },
  { id: 'patentev', label: 'Patente Volo', image: 'patentev.png' },
  { id: 'patenten', label: 'Patente Nautica', image: 'patenten.png' },
  { id: 'caccia', label: 'Licenza caccia', image: 'caccia.png' },
  { id: 'documento', label: 'Documento', image: 'documento.png' },
  { id: 'creditcard', label: 'Carta di credito', image: 'creditcard.png' },
  { id: 'portoarmi', label: 'Licenza armi', image: 'portoarmi.png' },
  { id: 'permessoc', label: 'Passaporto CP', image: 'permessoc.png' },
  { id: 'passport', label: 'Passaporto OutCity', image: 'passport.png' },
  { id: 'lockpick', label: 'Grimaldello', image: 'lockpick.png' },
  { id: 'vehiclekey', label: 'Chiavi auto', image: 'vehiclekey.png' },
  { id: 'wallet', label: 'Portafoglio', image: 'wallet.png' },
  { id: 'valigiasoldi', label: 'Valigia', image: 'valigiasoldi.png' },
  { id: 'phone', label: 'Telefono', image: 'phone.png' },
  { id: 'radio', label: 'Radio', image: 'radio.png' },
  { id: 'bomb_big', label: 'bomb_big', image: 'bomb_big.png' },
  { id: 'nastroadesivo', label: 'Nastro adesivo', image: 'nastroadesivo.png' },
  { id: 'screwdriver', label: 'Cacciavite', image: 'screwdriver.png' },
  { id: 'printerdocument', label: 'Documento stampato', image: 'printerdocument.png' },
  { id: 'zat-notebook', label: 'Quaderno', image: 'zat-notebook.png' },
  { id: 'boxprimo', label: 'Ingredienti primi', image: 'box.png' },
  { id: 'boxsecondo', label: 'Ingredienti secondi', image: 'box.png' },
  { id: 'boxantipasti', label: 'Ingredienti antipasti', image: 'box.png' },
  { id: 'boxfastfood', label: 'Ingredienti fast food', image: 'box.png' },
  { id: 'boxdolci', label: 'Ingredienti dolci', image: 'box.png' },
  { id: 'boxbevande', label: 'Ingredienti bevande', image: 'box.png' },
  { id: 'boxarmi', label: 'Materiale armi', image: 'box.png' },
  { id: 'boxofficina', label: 'Materiale officina', image: 'box.png' },
  { id: 'burger', label: 'Burger', image: 'burger.png' },
  { id: 'cozzepatate', label: 'Cozze e patate', image: 'cozzepatate.png' },
  { id: 'insalatamista', label: 'Insalata mista', image: 'insalatamista.png' },
  { id: 'lasagna', label: 'Lasagna', image: 'lasagna.png' },
  { id: 'pastabolognese', label: 'Pasta alla bolognese', image: 'pastabolognese.png' },
  { id: 'salad_italian', label: 'Caprese', image: 'salad_italian.png' },
  { id: 'tagliatainsalata', label: 'Tagliata', image: 'tagliatainsalata.png' },
  { id: 'tiramisu_part', label: 'Tiramisù', image: 'tiramisu_part.png' },
  { id: 'vanilla_cake_part', label: 'Torta alla vaniglia', image: 'vanilla_cake_part.png' },
  { id: 'verduregrigliate', label: 'Verdure grigliate', image: 'verduregrigliate.png' },
  { id: 'classic_brownies_part', label: 'Brownie', image: 'classic_brownies_part.png' },
  { id: 'croissant', label: 'Croissant', image: 'croissant.png' },
  { id: 'eclaire', label: 'Eclaire', image: 'eclaire.png' },
  { id: 'sandwich', label: 'Sandwich', image: 'sandwich.png' },
  { id: 'strawberry_cheesecake', label: 'Cheesecake', image: 'strawberry_cheesecake.png' },
  { id: 'toast_d', label: 'Toast', image: 'toast_d.png' },
  { id: 'chocolate_cheesecake', label: 'Cheesecake', image: 'chocolate_cheesecake.png' },
  { id: 'inv_natchos', label: 'Nachos', image: 'inv_natchos.png' },
  { id: 'salad_caesar', label: 'Insalata caesar', image: 'salad_caesar.png' },
  { id: 'nasipadang', label: 'Nasipa', image: 'nasipadang.png' },
  { id: 'fastfood_tray_generic', label: 'Vassoio con menù', image: 'fastfood_tray_generic.png' },
  { id: 'frites', label: 'Patatine', image: 'frites.png' },
  { id: 'generic_chicken2', label: 'Chicken Burger', image: 'generic_chicken2.png' },
  { id: 'generic_chickenstick', label: 'Alette di pollo', image: 'generic_chickenstick.png' },
  { id: 'generic_nuggets', label: 'Nuggets di pollo', image: 'generic_nuggets.png' },
  { id: 'generic_sandwichham', label: 'Panino al prosciutto', image: 'generic_sandwichham.png' },
  { id: 'berry_cheesecake', label: 'Cheesecake', image: 'berry_cheesecake.png' },
  { id: 'cobbsalad', label: 'Insalata mista', image: 'cobbsalad.png' },
  { id: 'ice2', label: 'Gelato misto', image: 'ice2.png' },
  { id: 'shrimp_nuggets', label: 'Gamberetti', image: 'shrimp_nuggets.png' },
  { id: 'sandosandwich', label: 'Sandwich', image: 'sandosandwich.png' },
  { id: 'sushi', label: 'Sushi misto', image: 'sushi.png' },
  { id: 'tacos', label: 'Tacos', image: 'tacos.png' },
  { id: 'hawaii', label: 'Pizza hawaii', image: 'hawaii.png' },
  { id: 'marinara', label: 'Pizza marinara', image: 'marinara.png' },
  { id: 'margherita', label: 'Pizza margherita', image: 'margherita.png' },
  { id: 'diavola', label: 'Pizza diavola', image: 'diavola.png' },
  { id: 'quattroformaggi', label: 'Pizza quattro formaggi', image: 'quattroformaggi.png' },
  { id: 'pizza_seafood', label: 'Pizza marittima', image: 'pizza_seafood.png' },
  { id: 'burger_bleeder', label: 'Hamburger', image: 'burger_bleeder.png' },
  { id: 'burger_hotdog', label: 'Hotdog', image: 'burger_hotdog.png' },
  { id: 'carneasadafries', label: 'Asada', image: 'carneasadafries.png' },
  { id: 'grillcheese', label: 'Toast', image: 'grillcheese.png' },
  { id: 'bbq', label: 'Vassoio grigliata', image: 'bbq.png' },
  { id: 'burrito_a', label: 'Burrito', image: 'burrito_a.png' },
  { id: 'churros', label: 'Churros', image: 'churros.png' },
  { id: 'homemade_sandwich', label: 'Sandwich', image: 'homemade_sandwich.png' },
  { id: 'burger_cheese3', label: 'Hamburger', image: 'burger_cheese3.png' },
  { id: 'potato_gratin_part', label: 'Patate gratinate', image: 'potato_gratin_part.png' },
  { id: 'fastfood_tray_upnatom', label: 'Vassoio Menù', image: 'fastfood_tray_upnatom.png' },
  { id: 'frites_atome', label: 'Patatine', image: 'frites_atome.png' },
  { id: 'upnatom_cheese3', label: 'Cheese burger', image: 'upnatom_cheese3.png' },
  { id: 'upnatom_frenchTacos', label: 'Tacos', image: 'upnatom_frenchtacos.png' },
  { id: 'upnatom_hotdog', label: 'Hotdog', image: 'upnatom_hotdog.png' },
  { id: 'upnatom_nuggets', label: 'Nuggets', image: 'upnatom_nuggets.png' },
  { id: 'miniburger', label: 'Mini burger', image: 'miniburger.png' },
  { id: 'wing_hot', label: 'Alette piccanti', image: 'wing_hot.png' },
  { id: 'cbdfood', label: 'Pasta ai funghi', image: 'cbdfood.png' },
  { id: 'cbdsugar', label: 'Brownies', image: 'cbdsugar.png' },
  { id: 'chips_cheese', label: 'Patatine al formaggio', image: 'chips_cheese.png' },
  { id: 'chips_paprika', label: 'Patatine alla paprika', image: 'chips_paprika.png' },
  { id: 'chips_ribs', label: 'Patatine al BBQ', image: 'chips_ribs.png' },
  { id: 'chips_salt', label: 'Patatine con salsa', image: 'chips_salt.png' },
  { id: 'chips_supersalt', label: 'Patatine extra-salate', image: 'chips_supersalt.png' },
  { id: 'chips_habanero', label: 'Patatine piccanti', image: 'chips_habanero.png' },
  { id: 'chocolate_meteorite', label: 'Cioccolata: Meteorite', image: 'chocolate_meteorite.png' },
  { id: 'chocolate_captain', label: 'Cioccolata: Captain\'s Log', image: 'chocolate_captain.png' },
  { id: 'candy_zebra', label: 'Caramelle: Zebrabar', image: 'candy_zebra.png' },
  { id: 'candy_psqs', label: 'Caramelle: P\'s & Q\'s', image: 'candy_psqs.png' },
  { id: 'gum_peppermint', label: 'Gomme da masticare: Peppermint', image: 'gum_peppermint.png' },
  { id: 'gum_cinnamon', label: 'Gomme da masticare: Cinnamon', image: 'gum_cinnamon.png' },
  { id: 'gum_spearmint', label: 'Gomme da masticare: Spearmint', image: 'gum_spearmint.png' },
  { id: 'packetvanillaunicorn', label: 'Sacchetto', image: 'packetvanillaunicorn.png' },
  { id: 'packetbahama', label: 'Sacchetto', image: 'packetbahama.png' },
  { id: 'upnatome_menu', label: 'Sacchetto', image: 'upnatome_menu.png' },
  { id: 'packettequilala', label: 'Sacchetto', image: 'packettequilala.png' },
  { id: 'packetpizza', label: 'Sacchetto', image: 'packetpizza.png' },
  { id: 'sprunk', label: 'Sprunk', image: 'sprunk.png' },
  { id: 'cappuccino', label: 'Cappuccino', image: 'cappuccino.png' },
  { id: 'coffe_generic', label: 'Caffè', image: 'coffe_generic.png' },
  { id: 'coffe_meanmachine', label: 'Caffè', image: 'coffe_meanmachine.png' },
  { id: 'cocktail_morijo', label: 'Mojito', image: 'cocktail_morijo.png' },
  { id: 'cocktail_spritz', label: 'spritz', image: 'cocktail_spritz.png' },
  { id: 'cosmopolitan_2', label: 'Cosmopolitan', image: 'cosmopolitan_2.png' },
  { id: 'margarita_2', label: 'Margarita', image: 'margarita_2.png' },
  { id: 'drink_ecola', label: 'Bevanda', image: 'drink_ecola.png' },
  { id: 'cocktail_longisland', label: 'Long island', image: 'cocktail_longisland.png' },
  { id: 'mai_tai', label: 'Mai tai', image: 'mai_tai.png' },
  { id: 'pina_colada', label: 'Pina colada', image: 'pina_colada.png' },
  { id: 'cocktail_tequilasunrise', label: 'Tequila', image: 'cocktail_tequilasunrise.png' },
  { id: 'champagneluxe', label: 'Champagne', image: 'champagneluxe.png' },
  { id: 'wine', label: 'Vino', image: 'wine.png' },
  { id: 'coffe_upnatom', label: 'Caffè', image: 'coffe_upnatom.png' },
  { id: 'drink_atomehd', label: 'Bevanda', image: 'drink_atomehd.png' },
  { id: 'redvelvet', label: 'Red velvet', image: 'redvelvet.png' },
  { id: 'succodifrutta', label: 'Succo di frutta', image: 'succodifrutta.png' },
  { id: 'sexonthebeach_2', label: 'Sex on the beach', image: 'sexonthebeach_2.png' },
  { id: 'pisswasser', label: 'Birra Pißwasser', image: 'pisswasser.png' },
  { id: 'patriot', label: 'Birra Patriot', image: 'patriot.png' },
  { id: 'blarneys', label: 'Birra Blarneys', image: 'blarneys.png' },
  { id: 'logger', label: 'Birra Logger', image: 'logger.png' },
  { id: 'dusche', label: 'Birra Dusche Gold', image: 'dusche.png' },
  { id: 'jakey', label: 'Birra Jakey’s Lager', image: 'jakey.png' },
  { id: 'benedict', label: 'Birra Benedict Light', image: 'benedict.png' },
  { id: 'cbddrink', label: 'Acqua frizzante', image: 'cbddrink.png' },
  { id: 'bottle_cola', label: 'Cola', image: 'bottle_cola.png' },
  { id: 'bottle_junk', label: 'Junk', image: 'bottle_junk.png' },
  { id: 'bottle_orang', label: 'Orang Tang', image: 'bottle_orang.png' },
  { id: 'bottle_tonic', label: 'Acqua tonica', image: 'bottle_tonic.png' },
  { id: 'bottle_water', label: 'Acqua', image: 'bottle_water.png' },
  { id: 'bottle_sprunk', label: 'Sprunk', image: 'bottle_sprunk.png' },
  { id: 'can_cola', label: 'Lattina di cola', image: 'can_cola.png' },
  { id: 'can_orang', label: 'Lattina di Orang Tang', image: 'can_orang.png' },
  { id: 'can_junk', label: 'Lattina di Junk', image: 'can_junk.png' },
  { id: 'can_sprunk', label: 'Lattina di Sprunk', image: 'can_sprunk.png' },
  { id: 'can_logger', label: 'Lattina di Logger', image: 'can_logger.png' },
  { id: 'can_blarneys', label: 'Lattina di Blarneys', image: 'can_blarneys.png' },
  { id: 'can_hoplivion', label: 'Lattina di Hoplivion', image: 'can_hoplivion.png' },
  { id: 'can_cerbeza', label: 'Lattina di Cerbeza', image: 'can_cerbeza.png' },
  { id: 'coffee', label: 'Caffè', image: 'coffee.png' },
  { id: 'firework_1', label: 'Fuochi artificiali', image: 'firework_1.png' },
  { id: 'firework_2', label: 'Fuochi artificiali', image: 'firework_2.png' },
  { id: 'firework_3', label: 'Fuochi artificiali', image: 'firework_3.png' },
  { id: 'firework_4', label: 'Fuochi artificiali', image: 'firework_4.png' },
  { id: 'fontain_4', label: 'Fuochi artificiali', image: 'fontain_4.png' },
  { id: 'lighter', label: 'Accendino', image: 'lighter.png' },
  { id: 'lighter_zippo', label: 'Zippo', image: 'lighter_zippo.png' },
  { id: 'bcsd_badge', label: 'Distintivo Sceriffo', image: 'bcsd_badge.png' },
  { id: 'evidence_a', label: 'Prove di', image: 'evidence_a.png' },
  { id: 'evidence_az', label: 'Prove', image: 'evidence_az.png' },
  { id: 'evidence_b', label: 'Prove veicoli', image: 'evidence_b.png' },
  { id: 'evidence_n', label: 'Prove impatto', image: 'evidence_n.png' },
  { id: 'evidence_ne', label: 'Prove impronte', image: 'evidence_ne.png' },
  { id: 'evidence_r', label: 'Prove Sanguigne', image: 'evidence_r.png' },
  { id: 'evidence_ro', label: 'Prove', image: 'evidence_ro.png' },
  { id: 'evidence_v', label: 'Prove droga', image: 'evidence_v.png' },
  { id: 'fbi', label: 'Distintivo FBI', image: 'fbi.png' },
  { id: 'instant_camera', label: 'Fotocamera', image: 'instant_camera.png' },
  { id: 'k9', label: 'Fischietto K9', image: 'k9.png' },
  { id: 'lspd_badge', label: 'Distintivo Polizia', image: 'lspd_badge.png' },
  { id: 'megaphone', label: 'Megafono', image: 'megaphone.png' },
  { id: 'photo', label: 'Fotografia', image: 'photo.png' },
  { id: 'police_cad', label: 'Tablet FDO', image: 'police_cad.png' },
  { id: 'police_cadb', label: 'Tablet FDO rotto', image: 'police_cadb.png' },
  { id: 'report_evidence', label: 'Rapporto prove', image: 'report_evidence.png' },
  { id: 'police_shield', label: 'Scudo polizia', image: 'police_shield.png' },
  { id: 'police_bodycam', label: 'Bodycam', image: 'police_bodycam.png' },
  { id: 'police_bodycamb', label: 'Bodycam rotta', image: 'police_bodycamb.png' },
  { id: 'police_snakecam', label: 'Camera serpente', image: 'police_snakecam.png' },
  { id: 'finger_scanner', label: 'Rilevatore Impronte', image: 'finger_scanner.png' },
  { id: 'breath_alcohol_tester', label: 'Alcol test', image: 'breath_alcohol_tester.png' },
  { id: 'wool', label: 'Lana', image: 'wool.png' },
  { id: 'fabric', label: 'Gomitolo', image: 'fabric.png' },
  { id: 'clothe', label: 'Vestiti', image: 'clothe.png' },
  { id: 'wood', label: 'Legno', image: 'wood.png' },
  { id: 'cutted_wood', label: 'Legno lavorato', image: 'cutted_wood.png' },
  { id: 'packaged_plank', label: 'Legno confezionato', image: 'packaged_plank.png' },
  { id: 'petrol', label: 'Petrolio', image: 'petrol.png' },
  { id: 'petrol_raffin', label: 'Petrolio Raffinato', image: 'petrol_raffin.png' },
  { id: 'essence', label: 'Carburante', image: 'essence.png' },
  { id: 'stone', label: 'Pietra', image: 'stone.png' },
  { id: 'washed_stone', label: 'Pietra lavata', image: 'washed_stone.png' },
  { id: 'copper', label: 'Rame grezzo', image: 'copper.png' },
  { id: 'iron', label: 'Ferro grezzo', image: 'iron.png' },
  { id: 'gold', label: 'Oro grezzo', image: 'gold.png' },
  { id: 'diamond', label: 'Diamante', image: 'diamond.png' },
  { id: 'alive_chicken', label: 'Pollo vivo', image: 'alive_chicken.png' },
  { id: 'slaughtered_chicken', label: 'Pollo morto', image: 'slaughtered_chicken.png' },
  { id: 'packaged_chicken', label: 'Pollo confezionato', image: 'packaged_chicken.png' },
  { id: 'racing_tablet', label: 'Tablet Gare', image: 'racing_tablet.png' },
  { id: 'casino_beer', label: 'Birra casino', image: 'beer_stronzo.png' },
  { id: 'casino_burger', label: 'Burger casino', image: 'burger.png' },
  { id: 'casino_chips', label: 'Fiches', image: 'casino_chips.png' },
  { id: 'casino_coffee', label: 'Caffe casino', image: 'coffeecup_a.png' },
  { id: 'casino_coke', label: 'Cola casino', image: 'casino_coke.png' },
  { id: 'casino_donut', label: 'Donut casino', image: 'donut_b.png' },
  { id: 'casino_ego_chaser', label: 'Ego Chaser casino', image: 'casino_ego_chaser.png' },
  { id: 'casino_luckypotion', label: 'Lucky Potion Casino', image: 'casino_luckypotion.png' },
  { id: 'casino_psqs', label: 'Casino Ps & Qs', image: 'casino_psqs.png' },
  { id: 'casino_sandwich', label: 'Sandwich Casino', image: 'sandwich.png' },
  { id: 'sextoy', label: 'Sextoy', image: 'sextoy.png' },
  { id: 'condom', label: 'Preservativi: Soth Lags', image: 'condom.png' },
  { id: 'medicine_laxmax', label: 'Medicine: Lax to the Max', image: 'medicine_laxmax.png' },
  { id: 'medicine_alcopatch', label: 'Medicine: AlcoPatch', image: 'medicine_alcopatch.png' },
  { id: 'medicine_mollis', label: 'Medicine: Mollis', image: 'medicine_mollis.png' },
  { id: 'medicine_betta', label: 'Medicine: Betta', image: 'medicine_betta.png' },
  { id: 'cigs_redwood', label: 'Sigarette: Redwood', image: 'cigs_redwood.png' },
  { id: 'cigs_redwood2', label: 'Sigarette: Redwood2', image: 'cigs_redwood2.png' },
  { id: 'cigs_debonaireb', label: 'Sigarette: Debonaire Blue', image: 'cigs_debonaireb.png' },
  { id: 'cigs_debonaireg', label: 'Sigarette: Debonaire Green', image: 'cigs_debonaireg.png' },
  { id: 'cigs_cardiaque', label: 'Sigarette: Cardiaque', image: 'cigs_cardiaque.png' },
  { id: 'cigs_69brand', label: 'Sigarette: 69Brand', image: 'cigs_69brand.png' },
  { id: 'cigs_cok', label: 'Sigarette: CoK', image: 'cigs_cok.png' },
  { id: 'cigs_estancia', label: 'Sigarette: Estancia', image: 'cigs_estancia.png' },
  { id: 'levonorgestrel', label: 'Levonorgestrel', image: 'levonorgestrel.png' },
  { id: 'mifepristone', label: 'Mifepristone', image: 'mifepristone.png' },
  { id: 'testpack', label: 'Test gravidanza', image: 'testpack.png' },
  { id: 'viagra', label: 'Viagra', image: 'viagra.png' },
  { id: 'oiltank', label: 'Serbatoio', image: 'oil.png' },
  { id: 'oil_bottle', label: 'Bottiglia Olio', image: 'Olive_oil.png' },
  { id: 'nail_bag', label: 'Borsa con chiodi', image: 'nail_bag.png' },
  { id: 'fire_extinguisher', label: 'Estintore', image: 'fire_extinguisher.png' },
  { id: 'torture_kit', label: 'Kit tortura', image: 'torture_kit.png' },
  { id: 'drone', label: 'Drone', image: 'drone.png' },
  { id: 'emergencydrone', label: 'Drone emergenza', image: 'emergencydrone.png' },
  { id: 'metaldetector', label: 'Metal Detector', image: 'metaldetector.png' },
  { id: 'binocolo', label: 'Binocolo', image: 'binocolo.png' },
  { id: 'remotecontrol', label: 'Telecomando', image: 'remotecontrol.png' },
  { id: 'headbag', label: 'Sacchetto', image: 'headbag.png' },
  { id: 'bt_c4', label: 'Carica di C4 (Portavalori)', image: 'bt_c4.png' },
  { id: 'bt_hackdevice', label: 'Dispositivo hacking (Portavalori)', image: 'bt_hackdevice.png' },
  { id: 'bt_gastank', label: 'Gas soporifero (portavalori)', image: 'bt_gastank.png' },
  { id: 'outfitbag', label: 'Borsone vestiti', image: 'outfitbag.png' },
  { id: 'joint', label: 'Joint', image: 'joint.png' },
  { id: 'scatolacartine', label: 'Cartine lunghe', image: 'scatolacartine.png' },
  { id: 'cartina', label: 'Cartina', image: 'cartina.png' },
  { id: 'shovel', label: 'Pala', image: 'shovel.png' },
  { id: 'fertilizer', label: 'Fertilizzante', image: 'fertilizer.png' },
  { id: 'watering_can', label: 'Annaffiatoio', image: 'watering_can.png' },
  { id: 'coca_seed', label: 'Seme di cocaina', image: 'coca_seed.png' },
  { id: 'tobacco_leaf', label: 'Foglia di tabacco', image: 'tobacco_leaf.png' },
  { id: 'tobacco', label: 'Tabacco lavorato', image: 'tobacco.png' },
  { id: 'weed_leaf_cbd', label: 'Foglia di cbd', image: 'weed_leaf_cbd.png' },
  { id: 'weed_bag_cbd', label: 'Sacchetto di cbd', image: 'weed_bag_cbd.png' },
  { id: 'cannettacbd', label: 'Joint CBD', image: 'cannettacbd.png' },
  { id: 'weed_leaf_marijuana', label: 'Foglia di marijuana', image: 'weed_leaf_marijuana.png' },
  { id: 'weed_marijuana_seed', label: 'Seme di marijuana', image: 'weed_marijuana_seed.png' },
  { id: 'poppy_seed', label: 'Seme di papavero', image: 'poppy_seed.png' },
  { id: 'poppy_opium', label: 'Oppio', image: 'poppy_opium.png' },
  { id: 'tomato_seed', label: 'Seme di pomodoro', image: 'tomato_seed.png' },
  { id: 'tomato', label: 'Pomodoro', image: 'tomato.png' },
  { id: 'cotton_seed', label: 'Seme di cotone', image: 'cotton_seed.png' },
  { id: 'cotton', label: 'Cotone', image: 'cotton.png' },
  { id: 'potato_seed', label: 'Seme di patata', image: 'potato_seed.png' },
  { id: 'potato', label: 'Patata', image: 'potato.png' },
  { id: 'ovettohashish', label: 'Ovulo di hashish', image: 'ovettohashish.png' },
  { id: 'panettahashish', label: 'Panetta di hashish', image: 'panettahashish.png' },
  { id: 'pseudoephedrine', label: 'Pseudoefedrina', image: 'pseudoephedrine.png' },
  { id: 'anhydrous_ammonia', label: 'Ammoniaca anidra', image: 'anhydrous_ammonia.png' },
  { id: 'small_fan', label: 'Ventilatore piccolo', image: 'small_fan.png' },
  { id: 'standing_fan', label: 'Ventilatore a piantana', image: 'standing_fan.png' },
  { id: 'unpackaged_meth', label: 'Metanfetamina', image: 'unpackaged_meth.png' },
  { id: 'water_lab_bottle', label: 'Tanica grande acqua', image: 'water_lab_bottle.png' },
  { id: 'weed_baggy', label: 'Bustina di erba', image: 'weed_baggy.png' },
  { id: 'weed_dried_leaf_marijuana', label: 'Foglia di marijuana essiccata', image: 'weed_dried_leaf_marijuana.png' },
  { id: 'coca_gaso_infused', label: 'Coca tagliata con benzina', image: 'coca_gaso_infused.png' },
  { id: 'coca_infused_liquid', label: 'Cocaina liquida', image: 'coca_infused_liquid.png' },
  { id: 'coca_leaf_powder', label: 'Polvere di foglie di coca', image: 'coca_leaf_powder.png' },
  { id: 'coca_leaves', label: 'Foglia di cocaina', image: 'coca_leaves.png' },
  { id: 'coca_powder', label: 'Cocaina in polvere', image: 'coca_powder.png' },
  { id: 'coke_baggy', label: 'Bustina di cocaina', image: 'coke_baggy.png' },
  { id: 'ero_baggy', label: 'Bustina di eroina', image: 'ero_baggy.png' },
  { id: 'coke_brick', label: 'Panetto di cocaina', image: 'coke_brick.png' },
  { id: 'coke_filter', label: 'Coke Filter', image: 'coke_filter.png' },
  { id: 'weed_light', label: 'Lampada UV Marijuana', image: 'weed_light.png' },
  { id: 'dirt_bag', label: 'Terriccio', image: 'fertilizer.png' },
  { id: 'drug_phone', label: 'Telefono Dokia', image: 'drug_phone.png' },
  { id: 'empty_m_bag', label: 'Sacchetto vuoto', image: 'empty_m_bag.png' },
  { id: 'empty_pot', label: 'Vaso vuoto', image: 'empty_pot.png' },
  { id: 'hammer', label: 'Martello', image: 'hammer.png' },
  { id: 'hydrochloric_acid', label: 'Acido cloridrico', image: 'hydrochloric_acid.png' },
  { id: 'weed_spray_bottle', label: 'Spray per marijuana', image: 'watering_can.png' },
  { id: 'lab_coat', label: 'Tuta da laboratorio', image: 'lab_coat.png' },
  { id: 'lithium', label: 'Litio', image: 'lithium.png' },
  { id: 'methamphetamine_base', label: 'Meth liquida', image: 'methamphetamine_base.png' },
  { id: 'methamphetamine_crystal', label: 'Cristallo di meth', image: 'methamphetamine_crystal.png' },
  { id: 'methamphetamine_hydrochloride', label: 'Meth cloridrata', image: 'hydrochloric_acid.png' },
  { id: 'meth_baggy', label: 'Bustina di meth', image: 'meth_baggy.png' },
  { id: 'meth_oil', label: 'Olio per meth', image: 'meth_oil.png' },
  { id: 'microwave', label: 'Microonde', image: 'microwave.png' },
  { id: 'weed_fertilizer', label: 'Fertilizzante marijuana', image: 'fertilizer.png' },
  { id: 'red_phosphorus', label: 'Fosforo rosso', image: 'red_phosphorus.png' },
  { id: 'glass_cutter', label: 'Compasso taglia-vetro', image: 'glass_cutter.png' },
  { id: 'giant_gem', label: 'Gemma preziosa', image: 'giant_gem.png' },
  { id: 'diamond_necklace', label: 'Collier di diamanti', image: 'diamond_necklace.png' },
  { id: 'diamond_ring', label: 'Anello con diamante', image: 'diamond_ring.png' },
  { id: 'diamond_earring', label: 'Orecchino in diamanti', image: 'diamond_earring.png' },
  { id: 'ruby_ring', label: 'Anello con rubino', image: 'ruby_ring.png' },
  { id: 'ruby_necklace', label: 'Collier di rubini', image: 'ruby_necklace.png' },
  { id: 'ruby_earring', label: 'Orecchino in rubino', image: 'ruby_earring.png' },
  { id: 'sapphire_ring', label: 'Anello con zaffiro', image: 'sapphire_ring.png' },
  { id: 'sapphire_necklace', label: 'Collier di zaffiri', image: 'sapphire_necklace.png' },
  { id: 'sapphire_earring', label: 'Orecchino in zaffiro', image: 'sapphire_earring.png' },
  { id: 'emerald_ring', label: 'Anello con smeraldo', image: 'emerald_ring.png' },
  { id: 'emerald_necklace', label: 'Collier di smeraldi', image: 'emerald_necklace.png' },
  { id: 'emerald_earring', label: 'Orecchino in smeraldo', image: 'emerald_earring.png' },
  { id: 'pliers', label: 'Tronchesi', image: 'pliers.png' },
  { id: 'x_device', label: 'Flapper Hero', image: 'x_device.png' },
  { id: 'x_phone', label: 'X Phone', image: 'x_phone.png' },
  { id: 'vangelicokey', label: 'Vangelico Key', image: 'vangelicokey.png' },
  { id: 'x_stethoscope', label: 'X Stetoscopio', image: 'x_stethoscope.png' },
  { id: 'x_hammer', label: 'X Martello', image: 'x_hammer.png' },
  { id: 'box_of_jewelry', label: 'Portagioie', image: 'box_of_jewelry.png' },
  { id: 'laserdrill', label: 'Trapano al laser', image: 'laserdrill.png' },
  { id: 'x_circuittester', label: 'Tester circuiti elettrici', image: 'x_circuittester.png' },
  { id: 'x_fingerprintbag', label: 'Busta per impronte digitali', image: 'x_fingerprintbag.png' },
  { id: 'x_fingerprinttape', label: 'Nastro per impronte digitali', image: 'x_fingerprinttape.png' },
  { id: 'fmkey', label: 'Chiave FM', image: 'fmkey.png' },
  { id: 'gasmask', label: 'Maschera anti-gas', image: 'gasmask.png' },
  { id: 'nightvision', label: 'Visore notturno', image: 'nightvision.png' },
  { id: 'painting', label: 'Dipinto', image: 'painting.png' },
  { id: 'television', label: 'Televisore', image: 'television.png' },
  { id: 'coffee_machine', label: 'Macchinetta Caffe', image: 'coffee_machine.png' },
  { id: 'laptop', label: 'Portatile', image: 'laptop.png' },
  { id: 'console', label: 'Console', image: 'console.png' },
  { id: 'music_player', label: 'Impianto Audio', image: 'music_player.png' },
  { id: 'orologio', label: 'Orologio', image: 'orologio.png' },
  { id: 'evape1', label: 'E-Vape + Atomizer', image: 'evape1.png' },
  { id: 'evape2', label: 'Smoke + Atomizer', image: 'evape2.png' },
  { id: 'vapesuitcase', label: 'Vape Suitcase', image: 'vapesuitcase.png' },
  { id: 'blue_stickevape', label: 'Blue Stick E-Vape', image: 'blue_stickevape.png' },
  { id: 'red_stickevape', label: 'Red Stick E-Vape', image: 'red_stickevape.png' },
  { id: 'green_stickevape', label: 'Green Stick E-Vape', image: 'green_stickevape.png' },
  { id: 'pink_stickevape', label: 'Pink Stick E-Vape', image: 'pink_stickevape.png' },
  { id: 'lightgrey_stickevape', label: 'Light Grey Stick E-Vape', image: 'lightgrey_stickevape.png' },
  { id: 'black_stickevape', label: 'Black Stick E-Vape', image: 'black_stickevape.png' },
  { id: 'orange_stickevape', label: 'Orange Stick E-Vape', image: 'orange_stickevape.png' },
  { id: 'yellow_stickevape', label: 'Yellow Stick E-Vape', image: 'yellow_stickevape.png' },
  { id: 'blue_sumovape', label: 'Blue Sumo', image: 'blue_sumovape.png' },
  { id: 'red_sumovape', label: 'Red Sumo', image: 'red_sumovape.png' },
  { id: 'green_sumovape', label: 'Green Sumo', image: 'green_sumovape.png' },
  { id: 'pink_sumovape', label: 'Pink Sumo', image: 'pink_sumovape.png' },
  { id: 'lightgrey_sumovape', label: 'Light Grey Sumo', image: 'lightgrey_sumovape.png' },
  { id: 'black_sumovape', label: 'Black Sumo', image: 'black_sumovape.png' },
  { id: 'orange_sumovape', label: 'Orange Sumo', image: 'orange_sumovape.png' },
  { id: 'yellow_sumovape', label: 'Yellow Sumo', image: 'yellow_sumovape.png' },
  { id: 'blue_vaporglowvape', label: 'Blue VaporGlow', image: 'blue_vaporglowvape.png' },
  { id: 'red_vaporglowvape', label: 'Red VaporGlow', image: 'red_vaporglowvape.png' },
  { id: 'green_vaporglowvape', label: 'Green VaporGlow', image: 'green_vaporglowvape.png' },
  { id: 'pink_vaporglowvape', label: 'Pink VaporGlow', image: 'pink_vaporglowvape.png' },
  { id: 'lightgrey_vaporglowvape', label: 'Light Grey VaporGlow', image: 'lightgrey_vaporglowvape.png' },
  { id: 'black_vaporglowvape', label: 'Black VaporGlow', image: 'black_vaporglowvape.png' },
  { id: 'orange_vaporglowvape', label: 'Orange VaporGlow', image: 'orange_vaporglowvape.png' },
  { id: 'yellow_vaporglowvape', label: 'Yellow VaporGlow', image: 'yellow_vaporglowvape.png' },
  { id: 'sand_evapebox', label: 'Sand E-Vape Box', image: 'sand_evapebox.png' },
  { id: 'black_evapebox', label: 'Black E-Vape Box', image: 'black_evapebox.png' },
  { id: 'redblack_evapebox', label: 'Red & Black E-Vape Box', image: 'redblack_evapebox.png' },
  { id: 'cyan_evapebox', label: 'Cyan E-Vape Box', image: 'cyan_evapebox.png' },
  { id: 'redwhite_evapebox', label: 'Red & White E-Vape Box', image: 'redwhite_evapebox.png' },
  { id: 'grey_evapebox', label: 'Grey E-Vape Box', image: 'grey_evapebox.png' },
  { id: 'blue_smokebox', label: 'Blue Smoke Box', image: 'blue_smokebox.png' },
  { id: 'red_smokebox', label: 'Red Smoke Box', image: 'red_smokebox.png' },
  { id: 'green_smokebox', label: 'Green Smoke Box', image: 'green_smokebox.png' },
  { id: 'pink_smokebox', label: 'Pink Smoke Box', image: 'pink_smokebox.png' },
  { id: 'lightblue_smokebox', label: 'L. Blue Smoke Box', image: 'lightblue_smokebox.png' },
  { id: 'black_smokebox', label: 'Black Smoke Box', image: 'black_smokebox.png' },
  { id: 'orange_smokebox', label: 'Orange Smoke Box', image: 'orange_smokebox.png' },
  { id: 'yellow_smokebox', label: 'Yellow Smoke Box', image: 'yellow_smokebox.png' },
  { id: 'silver_longatomizer', label: 'Long Silver Atomizer', image: 'silver_longatomizer.png' },
  { id: 'red_longatomizer', label: 'Long Red Atomizer', image: 'red_longatomizer.png' },
  { id: 'blue_longatomizer', label: 'Long Blue Atomizer', image: 'blue_longatomizer.png' },
  { id: 'green_longatomizer', label: 'Long Green Atomizer', image: 'green_longatomizer.png' },
  { id: 'pink_longatomizer', label: 'Long Pink Atomizer', image: 'pink_longatomizer.png' },
  { id: 'grey_longatomizer', label: 'Long Grey Atomizer', image: 'grey_longatomizer.png' },
  { id: 'black_longatomizer', label: 'Long Black Atomizer', image: 'black_longatomizer.png' },
  { id: 'orange_longatomizer', label: 'Long Orange Atomizer', image: 'orange_longatomizer.png' },
  { id: 'yellow_longatomizer', label: 'Long Yellow Atomizer', image: 'yellow_longatomizer.png' },
  { id: 'silver_shortatomizer', label: 'Short Silver Atomizer', image: 'silver_shortatomizer.png' },
  { id: 'red_shortatomizer', label: 'Short Red Atomizer', image: 'red_shortatomizer.png' },
  { id: 'blue_shortatomizer', label: 'Short Blue Atomizer', image: 'blue_shortatomizer.png' },
  { id: 'green_shortatomizer', label: 'Short Green Atomizer', image: 'green_shortatomizer.png' },
  { id: 'pink_shortatomizer', label: 'Short Pink Atomizer', image: 'pink_shortatomizer.png' },
  { id: 'grey_shortatomizer', label: 'Short Grey Atomizer', image: 'grey_shortatomizer.png' },
  { id: 'black_shortatomizer', label: 'Short Black Atomizer', image: 'black_shortatomizer.png' },
  { id: 'orange_shortatomizer', label: 'Short Orange Atomizer', image: 'orange_shortatomizer.png' },
  { id: 'yellow_shortatomizer', label: 'Short Yellow Atomizer', image: 'yellow_shortatomizer.png' },
  { id: 'silver_notankatomizer', label: 'Silver NO-Tank Atomizer', image: 'silver_notankatomizer.png' },
  { id: 'gold_notankatomizer', label: 'Gold NO-Tank Atomizer', image: 'gold_notankatomizer.png' },
  { id: 'black_notankatomizer', label: 'Black NO-Tank Atomizer', image: 'black_notankatomizer.png' },
  { id: 'red_notankatomizer', label: 'Red NO-Tank Atomizer', image: 'red_notankatomizer.png' },
  { id: 'liquid_sweettemptation', label: 'Liquid: Sweet Temptation', image: 'liquid_sweettemptation.png' },
  { id: 'liquid_iceberg', label: 'Liquid: Iceberg', image: 'liquid_iceberg.png' },
  { id: 'liquid_snoopify', label: 'Liquid: Snoopify', image: 'liquid_snoopify.png' },
  { id: 'liquid_goldtobacco', label: 'Liquid: Goldtobacco', image: 'liquid_goldtobacco.png' },
  { id: 'liquid_fruitytrip', label: 'Liquid: FruityTrip', image: 'liquid_fruitytrip.png' },
  { id: 'liquid_candybomb', label: 'Liquid: CandyBomb', image: 'liquid_candybomb.png' },
  { id: 'liquid_sensei', label: 'Liquid: Sensei', image: 'liquid_sensei.png' },
  { id: 'liquid_blueberry', label: 'Liquid: Blue Berry', image: 'liquid_blueberry.png' },
  { id: 'smokebox_cardboard', label: 'Smoke Box Cardboard', image: 'smokebox_cardboard.png' },
  { id: 'evape1_cardboard', label: 'E-Vape Stick Cardboard', image: 'evape1_cardboard.png' },
  { id: 'evape2_cardboard', label: 'E-Vape Box Cardboard', image: 'evape2_cardboard.png' },
  { id: 'sumo_cardboard', label: 'Sumo Vape Cardboard', image: 'sumo_cardboard.png' },
  { id: 'vaporglow_cardboard', label: 'VaporGlow Cardboard', image: 'vaporglow_cardboard.png' },
  { id: 'box_black_phone', label: 'Ifruit 16', image: 'box_black_phone.png' },
  { id: 'box_camera', label: 'Ifruit Camera', image: 'box_camera.png' },
  { id: 'box_remote', label: 'Telecomando', image: 'box_remote.png' },
  { id: 'box_tablette', label: 'Tablet', image: 'box_tablette.png' },
  { id: 'box_old_Phone', label: 'Ifruit 2', image: 'box_old_phone.png' },
  { id: 'box_talky', label: 'Radio', image: 'box_talky.png' },
  { id: 'box_laptop', label: 'Laptop', image: 'box_laptop.png' },
  { id: 'empty_digital_box', label: 'Scatola vuota', image: 'empty_digital_box.png' },
  { id: 'armbrace', label: 'Tutore braccio', image: 'armbrace.png' },
  { id: 'morphine10', label: 'Morfina 10mg', image: 'morphine10.png' },
  { id: 'morphine30', label: 'Morfine 30mg', image: 'morphine30.png' },
  { id: 'neckbrace', label: 'Collare', image: 'neckbrace.png' },
  { id: 'paracetamol', label: 'Paracetamolo', image: 'paracetamol.png' },
  { id: 'firstaid', label: 'Kit primo soccorso', image: 'firstaid.png' },
  { id: 'wheelchair', label: 'Sedia a rotelle', image: 'wheelchair.png' },
  { id: 'saline', label: 'Soluzione salina', image: 'saline.png' },
  { id: 'xray', label: 'Scanner Raggi-X', image: 'xray.png' },
  { id: 'legbrace', label: 'Tutore per gamba', image: 'legbrace.png' },
  { id: 'stretcher', label: 'Barella', image: 'stretcher.png' },
  { id: 'syringe', label: 'Siringa', image: 'syringe.png' },
  { id: 'lucas3', label: 'Dispositivo per massaggio cardiaco', image: 'lucas3.png' },
  { id: 'medicalbag', label: 'Borsone medico', image: 'medicalbag.png' },
  { id: 'medicinebox', label: 'Valigetta medicinali', image: 'medicinebox.png' },
  { id: 'medikit', label: 'Medikit', image: 'medikit.png' },
  { id: 'bodybandage', label: 'Bende per corpo', image: 'bodybandage.png' },
  { id: 'tcgpack', label: 'Pacchetto di carte collezionabili', image: 'tcgpack.png' },
  { id: 'tcgcard', label: 'Carta collezionabile', image: 'tcgcard.png' },
  { id: 'binder', label: 'Raccoglitore per carte', image: 'binder.png' },
  { id: 'radiocar', label: 'radiocar gray style', image: 'radiocar.png' },
  { id: 'radiocar_blue', label: 'radiocar blue style', image: 'radiocar_blue.png' },
  { id: 'engine_oil', label: 'Olio Motore', image: 'engine_oil.png' },
  { id: 'tyre_replacement', label: 'Sostituzione Pneumatici', image: 'tyre_replacement.png' },
  { id: 'clutch_replacement', label: 'Sostituzione Frizione', image: 'clutch_replacement.png' },
  { id: 'air_filter', label: 'Filtro dell\'Aria', image: 'air_filter.png' },
  { id: 'spark_plug', label: 'Candela', image: 'spark_plug.png' },
  { id: 'brakepad_replacement', label: 'Sostituzione Pastiglie Freni', image: 'brakepad_replacement.png' },
  { id: 'suspension_parts', label: 'Parti di Sospensione', image: 'suspension_parts.png' },
  { id: 'i4_engine', label: 'Motore I4', image: 'i4_engine.png' },
  { id: 'v6_engine', label: 'Motore V6', image: 'v6_engine.png' },
  { id: 'v8_engine', label: 'Motore V8', image: 'v8_engine.png' },
  { id: 'v12_engine', label: 'Motore V12', image: 'v12_engine.png' },
  { id: 'turbocharger', label: 'Turbina Maggiorata', image: 'turbocharger.png' },
  { id: 'ev_motor', label: 'Motore Elettrico', image: 'ev_motor.png' },
  { id: 'ev_battery', label: 'Batteria EV', image: 'ev_battery.png' },
  { id: 'ev_coolant', label: 'Liquido Refrigerante EV', image: 'ev_coolant.png' },
  { id: 'awd_drivetrain', label: 'Trasmissione Integrale (AWD)', image: 'awd_drivetrain.png' },
  { id: 'rwd_drivetrain', label: 'Trasmissione Posteriore (RWD)', image: 'rwd_drivetrain.png' },
  { id: 'fwd_drivetrain', label: 'Trasmissione Anteriore (FWD)', image: 'fwd_drivetrain.png' },
  { id: 'slick_tyres', label: 'Pneumatici Slick', image: 'slick_tyres.png' },
  { id: 'semi_slick_tyres', label: 'Pneumatici Semi-Slick', image: 'semi_slick_tyres.png' },
  { id: 'offroad_tyres', label: 'Pneumatici Fuoristrada', image: 'offroad_tyres.png' },
  { id: 'drift_tuning_kit', label: 'Kit Tuning Drift', image: 'drift_tuning_kit.png' },
  { id: 'ceramic_brakes', label: 'Freni in Ceramica', image: 'ceramic_brakes.png' },
  { id: 'lighting_controller', label: 'Controller Illuminazione', image: 'lighting_controller.png' },
  { id: 'stancing_kit', label: 'Kit Assetto', image: 'stancing_kit.png' },
  { id: 'cosmetic_part', label: 'Parti Estetiche', image: 'cosmetic_part.png' },
  { id: 'respray_kit', label: 'Kit Riverniciatura', image: 'respray_kit.png' },
  { id: 'vehicle_wheels', label: 'Set di Ruote per Veicoli', image: 'vehicle_wheels.png' },
  { id: 'tyre_smoke_kit', label: 'Kit Fumo Pneumatici', image: 'tyre_smoke_kit.png' },
  { id: 'extras_kit', label: 'Kit Extra', image: 'extras_kit.png' },
  { id: 'nitrous_bottle', label: 'Bombola di Nitro', image: 'nitrous_bottle.png' },
  { id: 'empty_nitrous_bottle', label: 'Bombola di Nitro Vuota', image: 'empty_nitrous_bottle.png' },
  { id: 'nitrous_install_kit', label: 'Kit Installazione Nitro', image: 'nitrous_install_kit.png' },
  { id: 'cleaning_kit', label: 'Kit Pulizia', image: 'cleaning_kit.png' },
  { id: 'repair_kit', label: 'Kit Riparazione', image: 'repair_kit.png' },
  { id: 'duct_tape', label: 'Nastro Adesivo Telato', image: 'duct_tape.png' },
  { id: 'performance_part', label: 'Parti Performance', image: 'performance_part.png' },
  { id: 'mechanic_tablet', label: 'Tablet Meccanico', image: 'mechanic_tablet.png' },
  { id: 'manual_gearbox', label: 'Cambio manuale', image: 'manual_gearbox.png' },
  { id: 'hand_mirror', label: 'Specchio', image: 'hand_mirror.png' },
  { id: 'lipstick_remover', label: 'Struccante', image: 'lipstick_remover.png' },
  { id: 'lipstick0', label: 'Rossetto', image: 'lipstick0.png' },
  { id: 'lipstick1', label: 'Rossetto', image: 'lipstick1.png' },
  { id: 'lipstick2', label: 'Rossetto', image: 'lipstick2.png' },
  { id: 'lipstick3', label: 'Rossetto', image: 'lipstick3.png' },
  { id: 'lipstick4', label: 'Rossetto', image: 'lipstick4.png' },
  { id: 'lipstick5', label: 'Rossetto', image: 'lipstick5.png' },
  { id: 'lipstick6', label: 'Rossetto', image: 'lipstick6.png' },
  { id: 'lipstick7', label: 'Rossetto', image: 'lipstick7.png' },
  { id: 'lipstick8', label: 'Rossetto', image: 'lipstick8.png' },
  { id: 'lipstick9', label: 'Rossetto', image: 'lipstick9.png' },
  { id: 'lipstick10', label: 'Rossetto', image: 'lipstick10.png' },
  { id: 'lipstick11', label: 'Rossetto', image: 'lipstick11.png' },
  { id: 'lipstick12', label: 'Rossetto', image: 'lipstick12.png' },
  { id: 'lipstick13', label: 'Rossetto', image: 'lipstick13.png' },
  { id: 'lipstick14', label: 'Rossetto', image: 'lipstick14.png' },
  { id: 'lipstick15', label: 'Rossetto', image: 'lipstick15.png' },
  { id: 'lipstick16', label: 'Rossetto', image: 'lipstick16.png' },
  { id: 'lipstick17', label: 'Rossetto', image: 'lipstick17.png' },
  { id: 'lipstick18', label: 'Rossetto', image: 'lipstick18.png' },
  { id: 'lipstick19', label: 'Rossetto', image: 'lipstick19.png' },
  { id: 'lipstick20', label: 'Rossetto', image: 'lipstick20.png' },
  { id: 'lipstick21', label: 'Rossetto', image: 'lipstick21.png' },
  { id: 'lipstick22', label: 'Rossetto', image: 'lipstick22.png' },
  { id: 'lipstick23', label: 'Rossetto', image: 'lipstick23.png' },
  { id: 'lipstick24', label: 'Rossetto', image: 'lipstick24.png' },
  { id: 'lipstick25', label: 'Rossetto', image: 'lipstick25.png' },
  { id: 'lipstick26', label: 'Rossetto', image: 'lipstick26.png' },
  { id: 'lipstick27', label: 'Rossetto', image: 'lipstick27.png' },
  { id: 'lipstick28', label: 'Rossetto', image: 'lipstick28.png' },
  { id: 'lipstick29', label: 'Rossetto', image: 'lipstick29.png' },
  { id: 'lipstick30', label: 'Rossetto', image: 'lipstick30.png' },
  { id: 'lipstick31', label: 'Rossetto', image: 'lipstick31.png' },
  { id: 'lipstick32', label: 'Rossetto', image: 'lipstick32.png' },
  { id: 'lipstick33', label: 'Rossetto', image: 'lipstick33.png' },
  { id: 'lipstick34', label: 'Rossetto', image: 'lipstick34.png' },
  { id: 'lipstick35', label: 'Rossetto', image: 'lipstick35.png' },
  { id: 'lipstick36', label: 'Rossetto', image: 'lipstick36.png' },
  { id: 'lipstick37', label: 'Rossetto', image: 'lipstick37.png' },
  { id: 'lipstick38', label: 'Rossetto', image: 'lipstick38.png' },
  { id: 'lipstick39', label: 'Rossetto', image: 'lipstick39.png' },
  { id: 'lipstick40', label: 'Rossetto', image: 'lipstick40.png' },
  { id: 'lipstick41', label: 'Rossetto', image: 'lipstick41.png' },
  { id: 'lipstick42', label: 'Rossetto', image: 'lipstick42.png' },
  { id: 'lipstick43', label: 'Rossetto', image: 'lipstick43.png' },
  { id: 'lipstick44', label: 'Rossetto', image: 'lipstick44.png' },
  { id: 'lipstick45', label: 'Rossetto', image: 'lipstick45.png' },
  { id: 'lipstick46', label: 'Rossetto', image: 'lipstick46.png' },
  { id: 'lipstick47', label: 'Rossetto', image: 'lipstick47.png' },
  { id: 'lipstick48', label: 'Rossetto', image: 'lipstick48.png' },
  { id: 'lipstick49', label: 'Rossetto', image: 'lipstick49.png' },
  { id: 'lipstick50', label: 'Rossetto', image: 'lipstick50.png' },
  { id: 'lipstick51', label: 'Rossetto', image: 'lipstick51.png' },
  { id: 'lipstick52', label: 'Rossetto', image: 'lipstick52.png' },
  { id: 'lipstick53', label: 'Rossetto', image: 'lipstick53.png' },
  { id: 'lipstick54', label: 'Rossetto', image: 'lipstick54.png' },
  { id: 'lipstick55', label: 'Rossetto', image: 'lipstick55.png' },
  { id: 'lipstick56', label: 'Rossetto', image: 'lipstick56.png' },
  { id: 'lipstick57', label: 'Rossetto', image: 'lipstick57.png' },
  { id: 'lipstick58', label: 'Rossetto', image: 'lipstick58.png' },
  { id: 'lipstick59', label: 'Rossetto', image: 'lipstick59.png' },
  { id: 'lipstick60', label: 'Rossetto', image: 'lipstick60.png' },
  { id: 'lipstick61', label: 'Rossetto', image: 'lipstick61.png' },
  { id: 'lipstick62', label: 'Rossetto', image: 'lipstick62.png' },
  { id: 'lipstick63', label: 'Rossetto', image: 'lipstick63.png' },
  { id: 'electronickit', label: 'Circuito elettronico', image: 'electronickit.png' },
  { id: 'jammerec', label: 'Jammer', image: 'jammerec.png' },
  { id: 'rope', label: 'Corda', image: 'rope.png' },
  { id: 'fishing_rod_normal', label: 'Canna da pesca standard', image: 'fishing_rod_normal.png' },
  { id: 'fishing_rod_sport', label: 'Canna da pesca sportiva', image: 'fishing_rod_sport.png' },
  { id: 'fishing_rod_advanced', label: 'Canna da pesca avanzata', image: 'fishing_rod_advanced.png' },
  { id: 'fishing_rod_super', label: 'Canna da pesca professionale', image: 'fishing_rod_super.png' },
  { id: 'fish1', label: 'Trota', image: 'fish1.png' },
  { id: 'fish2', label: 'Orata', image: 'fish2.png' },
  { id: 'fish3', label: 'Lavarello', image: 'fish3.png' },
  { id: 'fish4', label: 'Maingano', image: 'fish4.png' },
  { id: 'fish5', label: 'Ciclide', image: 'fish5.png' },
  { id: 'fish6', label: 'Danio', image: 'fish6.png' },
  { id: 'karpik', label: 'Carpa', image: 'karpik.png' },
  { id: 'shoe_shit', label: 'Scarpa rotta', image: 'shoe_shit.png' },
  { id: 'redline_bait', label: 'Redline Fishing Bait', image: 'redline_bait.png' },
  { id: 'corn_bait', label: 'Corn Fishing Bait', image: 'corn_bait.png' },
  { id: 'crab_bait', label: 'Crab Fishing Bait', image: 'crab_bait.png' },
  { id: 'dot_bait', label: 'Dot Fishing Bait', image: 'dot_bait.png' },
  { id: 'redline_bait', label: 'Redline Fishing Bait', image: 'redline_bait.png' },
  { id: 'shrimp_bait', label: 'Shrimp Fishing Bait', image: 'shrimp_bait.png' },
  { id: 'black_mamba', label: 'Black Mamba Fishing Bait', image: 'black_mamba.png' },
  { id: 'golden_fish_bait', label: 'Golden Fish Bait', image: 'golden_fish_bait.png' },
  { id: 'diving_gear', label: 'Diving Gear', image: 'diving_gear.png' },
  { id: 'treasure_shovel', label: 'Shovel', image: 'treasure_shovel.png' },
  { id: 'lucky_hat', label: 'Lucky Hat', image: 'lucky_hat.png' },
  { id: 'water_meter', label: 'Meter', image: 'water_meter.png' },
  { id: 'dry_station', label: 'Dry Station', image: 'dry_station.png' },
  { id: 'carp', label: 'Carp', image: 'carp.png' },
  { id: 'crab', label: 'Crab', image: 'crab.png' },
  { id: 'catfish', label: 'Catfish', image: 'catfish.png' },
  { id: 'tarpon', label: 'Tarpon', image: 'tarpon.png' },
  { id: 'barracuda', label: 'Barracuda', image: 'barracuda.png' },
  { id: 'discus', label: 'Discus', image: 'discus.png' },
  { id: 'snapper', label: 'Snapper', image: 'snapper.png' },
  { id: 'sturgeon', label: 'Sturgeon', image: 'sturgeon.png' },
  { id: 'mojarra_fish', label: 'Mojarra', image: 'mojarra_fish.png' },
  { id: 'bocachico_fish', label: 'Bocachico', image: 'bocachico_fish.png' },
  { id: 'disco_fish', label: 'Disco Fish', image: 'disco_fish.png' },
  { id: 'koi_fish', label: 'Koi Fish', image: 'koi_fish.png' },
  { id: 'angelfishemperror', label: 'Angel Fish Emperror', image: 'angelfishemperror.png' },
  { id: 'crystal_catfish', label: 'Crystal Catfish', image: 'crystal_catfish.png' },
  { id: 'flying_fish', label: 'Flying Fish', image: 'flying_fish.png' },
  { id: 'hammerhead', label: 'Hammerhead', image: 'hammerhead.png' },
  { id: 'anchor', label: 'Anchor', image: 'anchor.png' },
  { id: 'fishing_net', label: 'Fishing Net', image: 'fishing_net.png' },
  { id: 'fishing_net_plus', label: 'Fishing Net++', image: 'fishing_net_plus.png' },
  { id: 'crab_cage', label: 'Crab Cage', image: 'crab_cage.png' },
  { id: 'crab_cage_plus', label: 'Crab Cage++', image: 'crab_cage_plus.png' },
  { id: 'cartellina', label: 'Porta documenti', image: 'cartellina.png' },
  { id: 'cartellinadoc', label: 'Cartellina', image: 'cartellinadoc.png' },
  { id: 'indiziof', label: 'Lettera', image: 'heist_plan.png' },
  { id: 'indiziom', label: 'Lettera', image: 'heist_plan.png' },
  { id: 'numerotel', label: 'Foglietto', image: 'heist_plan.png' },
  { id: 'indiziovc', label: 'Lettera', image: 'heist_plan.png' },
  { id: 'indiziovj', label: 'Lettera', image: 'heist_plan.png' },
  { id: 'indizioa', label: 'Lettera', image: 'heist_plan.png' },
  { id: 'indizioh', label: 'Lettera', image: 'heist_plan.png' },
  { id: 'indiziorc', label: 'Lettera', image: 'heist_plan.png' },
  { id: 'progettoa', label: 'Progetto', image: 'blueprint.png' },
  { id: 'progettob', label: 'Progetto', image: 'blueprint.png' },
  { id: 'progettoc', label: 'Progetto', image: 'blueprint.png' },
  { id: 'progettod', label: 'Progetto', image: 'blueprint.png' },
  { id: 'progettoe', label: 'Progetto', image: 'blueprint.png' },
  { id: 'pianob', label: 'Planimetria', image: 'blueprint.png' },
  { id: 'pianoj', label: 'Planimetria', image: 'blueprint.png' },
  { id: 'indiziojdma', label: 'Lettera', image: 'blueprint.png' },
  { id: 'indiziojdmb', label: 'Lettera', image: 'blueprint.png' },
  { id: 'indiziojdmc', label: 'Lettera', image: 'blueprint.png' },
  { id: 'indiziojdmd', label: 'Lettera', image: 'blueprint.png' },
  { id: 'indiziojdmfinale', label: 'Lettera', image: 'indiziojdmfinale.png' },
  { id: 'indiziomech', label: 'Lettera', image: 'blueprint.png' },
  { id: 'bit', label: 'AvenoXcoin', image: 'bit.png' },
  { id: 'heist_papers', label: 'Documenti veicolo', image: 'heist_papers.png' },
  { id: 'shoesbox', label: 'Scatola scarpe', image: 'shoesbox.png' },
  { id: 'baglux', label: 'Borsa di lusso', image: 'baglux.png' },
  { id: 'bletter', label: 'Lettera', image: 'bletter.png' },
  { id: 'bpackage', label: 'Pacco', image: 'bpackage.png' },
  { id: 'batm_hacker', label: 'Hacking ATM', image: 'batm_hacker.png' },
  { id: 'bbag', label: 'Borsone', image: 'bbag.png' },
  { id: 'bbrick', label: 'Mattone', image: 'bbrick.png' },
  { id: 'assegno', label: 'Assegno', image: 'assegno.png' },
  { id: 'letterinaa', label: 'Torneo di skateboard', image: 'letterina.png' },
  { id: 'letterinab', label: 'Multa', image: 'letterina.png' },
  { id: 'letterinac', label: 'Lettera d’amore', image: 'letterina.png' },
  { id: 'letterinad', label: 'Lettera universitaria', image: 'letterina.png' },
  { id: 'letterinae', label: 'Cartolina', image: 'letterina.png' },
  { id: 'letterinaf', label: 'Cartolina', image: 'letterina.png' },
  { id: 'scratchcard', label: 'Gratta e vinci', image: 'scratchcard.png' },
  { id: 'cannasns', label: 'Canna SNS', image: 'cannasns.png' },
  { id: 'corposns', label: 'Corpo SNS', image: 'corposns.png' },
  { id: 'polvereds', label: 'Polvere da sparo', image: 'polvereds.png' },
  { id: 'antilag', label: 'Kit antilag', image: 'antilag.png' },
  { id: 'pd_licence_plate_flipper', label: 'Oscura targa', image: 'pd_licence_plate_flipper.png' },
  { id: 'blowpipe', label: 'Blowtorch', image: 'blowpipe.png' },
  { id: 'bread', label: 'Bread', image: 'bread.png' },
  { id: 'cannabis', label: 'Cannabis', image: 'cannabis.png' },
  { id: 'carokit', label: 'Body Kit', image: 'carokit.png' },
  { id: 'carotool', label: 'Tools', image: 'carotool.png' },
  { id: 'fish', label: 'Fish', image: 'fish.png' },
  { id: 'fixkit', label: 'Repair Kit', image: 'fixkit.png' },
  { id: 'fixtool', label: 'Repair Tools', image: 'fixtool.png' },
  { id: 'gazbottle', label: 'Gas Bottle', image: 'gazbottle.png' },
  { id: 'marijuana', label: 'Marijuana', image: 'marijuana.png' },
  { id: 'water', label: 'Water', image: 'water.png' },
  { id: 'bench_basic', label: 'Basic Crafting Bench', image: 'bench_basic.png' },
  { id: 'bench_advanced', label: 'Advanced Crafting Bench', image: 'bench_advanced.png' },
  { id: 'blueprint', label: 'blueprint', image: 'blueprint.png' },
  { id: 'armor_plates', label: 'Armor Plates', image: 'armor_plates.png' },
  { id: 'armor_repair_kit', label: 'Armor Repair Kit', image: 'armor_repair_kit.png' },
  { id: 'backpack_small', label: 'Small Backpack', image: 'backpack_small.png' },
  { id: 'backpack_medium', label: 'Medium Backpack', image: 'backpack_medium.png' },
  { id: 'backpack_large', label: 'Large Backpack', image: 'backpack_large.png' },
  { id: 'fakeplate', label: 'Fake Plate', image: 'fakeplate.png' },
  { id: 'fakeplate_remover', label: 'Original Plate', image: 'fakeplate_remover.png' },
  { id: 'car_contract', label: 'Car Contract', image: 'rentalpaper.png' },
  { id: 'tablethacker', label: 'Tablet Hacker', image: 'tablethacker.png' },
  { id: 'gold_tooth', label: 'Gold Tooth', image: 'gold_tooth.png' },
  { id: 'dirty_photo', label: 'Dity Photo', image: 'dirty_photo.png' },
  { id: 'chain', label: 'Chain', image: 'chain.png' },
  { id: 'medal', label: 'Medal', image: 'medal.png' },
  { id: 'rusted_tin', label: 'Rusted Tin', image: 'rusted_tin.png' },
  { id: 'nail', label: 'Nail', image: 'nail.png' },
  { id: 'ring', label: 'Ring', image: 'ring.png' },
  { id: 'vehicle_tyre', label: 'Vehicle Tyre', image: 'vehicle_tyre.png' },
  { id: 'vehicle_door', label: 'Vehicle Door', image: 'vehicle_door.png' },
];

const INVENTARIO_WEAPONS = [
  { id: 'WEAPON_BATTLERIFLE', label: 'Battle Rifle', image: 'weapon_battlerifle.png' },
  { id: 'WEAPON_SNOWLAUNCHER', label: 'Snowball Launcher', image: 'weapon_snowlauncher.png' },
  { id: 'WEAPON_TECPISTOL', label: 'Tactical SMG', image: 'weapon_tecpistol.png' },
  { id: 'WEAPON_ADVANCEDRIFLE', label: 'Advanced Rifle', image: 'weapon_advancedrifle.png' },
  { id: 'WEAPON_APPISTOL', label: 'AP Pistol', image: 'weapon_appistol.png' },
  { id: 'WEAPON_ASSAULTRIFLE', label: 'Assault Rifle', image: 'weapon_assaultrifle.png' },
  { id: 'WEAPON_ASSAULTRIFLE_MK2', label: 'Assault Rifle MK2', image: 'weapon_assaultrifle_mk2.png' },
  { id: 'WEAPON_ASSAULTSHOTGUN', label: 'Assault Shotgun', image: 'weapon_assaultshotgun.png' },
  { id: 'WEAPON_ASSAULTSMG', label: 'Assault SMG', image: 'weapon_assaultsmg.png' },
  { id: 'WEAPON_BALL', label: 'Ball', image: 'weapon_ball.png' },
  { id: 'WEAPON_BAT', label: 'Bat', image: 'weapon_bat.png' },
  { id: 'WEAPON_BATTLEAXE', label: 'Battle Axe', image: 'weapon_battleaxe.png' },
  { id: 'WEAPON_BOTTLE', label: 'Bottle', image: 'weapon_bottle.png' },
  { id: 'WEAPON_BULLPUPRIFLE', label: 'Bullpup Rifle', image: 'weapon_bullpuprifle.png' },
  { id: 'WEAPON_BULLPUPRIFLE_MK2', label: 'Bullpup Rifle MK2', image: 'weapon_bullpuprifle_mk2.png' },
  { id: 'WEAPON_BULLPUPSHOTGUN', label: 'Bullpup Shotgun', image: 'weapon_bullpupshotgun.png' },
  { id: 'WEAPON_BZGAS', label: 'BZ Gas', image: 'weapon_bzgas.png' },
  { id: 'WEAPON_CARBINERIFLE', label: 'Carbine Rifle', image: 'weapon_carbinerifle.png' },
  { id: 'WEAPON_CARBINERIFLE_MK2', label: 'Carbine Rifle MK2', image: 'weapon_carbinerifle_mk2.png' },
  { id: 'WEAPON_CERAMICPISTOL', label: 'Ceramic Pistol', image: 'weapon_ceramicpistol.png' },
  { id: 'WEAPON_PISTOLXM3', label: 'WM 29 Pistol', image: 'weapon_pistolxm3.png' },
  { id: 'WEAPON_COMBATMG', label: 'Combat MG', image: 'weapon_combatmg.png' },
  { id: 'WEAPON_COMBATMG_MK2', label: 'Combat MG MK2', image: 'weapon_combatmg_mk2.png' },
  { id: 'WEAPON_COMBATPDW', label: 'Combat PDW', image: 'weapon_combatpdw.png' },
  { id: 'WEAPON_COMBATPISTOL', label: 'Combat Pistol', image: 'weapon_combatpistol.png' },
  { id: 'WEAPON_COMBATSHOTGUN', label: 'Combat Shotgun', image: 'weapon_combatshotgun.png' },
  { id: 'WEAPON_COMPACTLAUNCHER', label: 'Compact Grenade Launcher', image: 'weapon_compactlauncher.png' },
  { id: 'WEAPON_COMPACTRIFLE', label: 'Compact Rifle', image: 'weapon_compactrifle.png' },
  { id: 'WEAPON_CROWBAR', label: 'Crowbar', image: 'weapon_crowbar.png' },
  { id: 'WEAPON_DAGGER', label: 'Dagger', image: 'weapon_dagger.png' },
  { id: 'WEAPON_DBSHOTGUN', label: 'Double Barrel Shotgun', image: 'weapon_dbshotgun.png' },
  { id: 'WEAPON_DOUBLEACTION', label: 'Double Action Revolver', image: 'weapon_doubleaction.png' },
  { id: 'WEAPON_EMPLAUNCHER', label: 'Compact EMP Launcher', image: 'weapon_emplauncher.png' },
  { id: 'WEAPON_FIREEXTINGUISHER', label: 'Fire Extinguisher', image: 'weapon_fireextinguisher.png' },
  { id: 'WEAPON_FIREWORK', label: 'Firework Launcher', image: 'weapon_firework.png' },
  { id: 'WEAPON_FLARE', label: 'Flare', image: 'weapon_flare.png' },
  { id: 'WEAPON_FLAREGUN', label: 'Flare Gun', image: 'weapon_flaregun.png' },
  { id: 'WEAPON_FLASHLIGHT', label: 'Flashlight', image: 'weapon_flashlight.png' },
  { id: 'WEAPON_GOLFCLUB', label: 'Golf Club', image: 'weapon_golfclub.png' },
  { id: 'WEAPON_ACIDPACKAGE', label: 'News papaer', image: 'weapon_acidpackage.png' },
  { id: 'WEAPON_GRENADE', label: 'Grenade', image: 'weapon_grenade.png' },
  { id: 'WEAPON_GRENADELAUNCHER', label: 'Grenade Launcher', image: 'weapon_grenadelauncher.png' },
  { id: 'WEAPON_GUSENBERG', label: 'Gusenberg', image: 'weapon_gusenberg.png' },
  { id: 'WEAPON_HAMMER', label: 'Hammer', image: 'weapon_hammer.png' },
  { id: 'WEAPON_HATCHET', label: 'Hatchet', image: 'weapon_hatchet.png' },
  { id: 'WEAPON_HEAVYRIFLE', label: 'Heavy Rifle', image: 'weapon_heavyrifle.png' },
  { id: 'WEAPON_HAZARDCAN', label: 'Hazard Can', image: 'weapon_hazardcan.png' },
  { id: 'WEAPON_METALDETECTOR', label: 'Metal Detector', image: 'weapon_metaldetector.png' },
  { id: 'WEAPON_HOMINGLAUNCHER', label: 'Homing Launcher', image: 'weapon_hominglauncher.png' },
  { id: 'WEAPON_FERTILIZERCAN', label: 'Fertilizer Can', image: 'weapon_fertilizercan.png' },
  { id: 'WEAPON_HEAVYPISTOL', label: 'Heavy Pistol', image: 'weapon_heavypistol.png' },
  { id: 'WEAPON_HEAVYSHOTGUN', label: 'Heavy Shotgun', image: 'weapon_heavyshotgun.png' },
  { id: 'WEAPON_HEAVYSNIPER', label: 'Heavy Sniper', image: 'weapon_heavysniper.png' },
  { id: 'WEAPON_HEAVYSNIPER_MK2', label: 'Heavy Sniper MK2', image: 'weapon_heavysniper_mk2.png' },
  { id: 'WEAPON_KNIFE', label: 'Knife', image: 'weapon_knife.png' },
  { id: 'WEAPON_KNUCKLE', label: 'Knuckle Dusters', image: 'weapon_knuckle.png' },
  { id: 'WEAPON_MACHETE', label: 'Machete', image: 'weapon_machete.png' },
  { id: 'WEAPON_MACHINEPISTOL', label: 'Machine Pistol', image: 'weapon_machinepistol.png' },
  { id: 'WEAPON_MARKSMANPISTOL', label: 'Marksman Pistol', image: 'weapon_marksmanpistol.png' },
  { id: 'WEAPON_MARKSMANRIFLE', label: 'Marksman Rifle', image: 'weapon_marksmanrifle.png' },
  { id: 'WEAPON_MARKSMANRIFLE_MK2', label: 'Marksman Rifle MK2', image: 'weapon_marksmanrifle_mk2.png' },
  { id: 'WEAPON_MG', label: 'Machine Gun', image: 'weapon_mg.png' },
  { id: 'WEAPON_MINIGUN', label: 'Minigun', image: 'weapon_minigun.png' },
  { id: 'WEAPON_MICROSMG', label: 'Micro SMG', image: 'weapon_microsmg.png' },
  { id: 'WEAPON_MILITARYRIFLE', label: 'Military Rifle', image: 'weapon_militaryrifle.png' },
  { id: 'WEAPON_MINISMG', label: 'Mini SMG', image: 'weapon_minismg.png' },
  { id: 'WEAPON_MOLOTOV', label: 'Molotov', image: 'weapon_molotov.png' },
  { id: 'WEAPON_MUSKET', label: 'Musket', image: 'weapon_musket.png' },
  { id: 'WEAPON_NAVYREVOLVER', label: 'Navy Revolver', image: 'weapon_navyrevolver.png' },
  { id: 'WEAPON_NIGHTSTICK', label: 'Nightstick', image: 'weapon_nightstick.png' },
  { id: 'WEAPON_KATANA', label: 'Katana', image: 'weapon_katana.png' },
  { id: 'WEAPON_SLEDGEHAMMER', label: 'Martello pneumatico', image: 'weapon_sledgehammer.png' },
  { id: 'WEAPON_PERFORATOR', label: 'Il Perforatore', image: 'weapon_perforator.png' },
  { id: 'WEAPON_BAYONETKNIFE', label: 'Coltello Baionetta', image: 'weapon_bayonetknife.png' },
  { id: 'WEAPON_BLUEBFKNIFE', label: 'Coltello Farfalla Blu Acciaio', image: 'weapon_bluebfknife.png' },
  { id: 'WEAPON_BFKNIFE', label: 'Coltello Farfalla Vaniglia', image: 'weapon_bfknife.png' },
  { id: 'WEAPON_CHBFKNIFE', label: 'Coltello Farfalla Case Hardened', image: 'weapon_chbfknife.png' },
  { id: 'WEAPON_CRIMSONBFKNIFE', label: 'Coltello Farfalla Cremisi', image: 'weapon_crimsonbfknife.png' },
  { id: 'WEAPON_FADEBFKNIFE', label: 'Coltello Farfalla Sfumato', image: 'weapon_fadebfknife.png' },
  { id: 'WEAPON_FLIPKNIFE', label: 'Coltello a Scatto', image: 'weapon_flipknife.png' },
  { id: 'WEAPON_FORESTBFKNIFE', label: 'Coltello Farfalla Foresta', image: 'weapon_forestbfknife.png' },
  { id: 'WEAPON_GUTKNIFE', label: 'Coltello da Sventramento', image: 'weapon_gutknife.png' },
  { id: 'WEAPON_HUNTSMANKNIFE', label: 'Coltello del Cacciatore', image: 'weapon_huntsmanknife.png' },
  { id: 'WEAPON_KARAMBITKNIFE', label: 'Coltello Karambit', image: 'weapon_karambitknife.png' },
  { id: 'WEAPON_SAFARIBFKNIFE', label: 'Coltello Farfalla Rete Safari', image: 'weapon_safaribfknife.png' },
  { id: 'WEAPON_SCORCHEDBFKNIFE', label: 'Coltello Farfalla Bruciato', image: 'weapon_scorchedbfknife.png' },
  { id: 'WEAPON_SLAUGHTERBFKNIFE', label: 'Coltello Farfalla Macello', image: 'weapon_slaughterbfknife.png' },
  { id: 'WEAPON_STAINEDRBFKNIFE', label: 'Coltello Farfalla Macchiato', image: 'weapon_stainedrbfknife.png' },
  { id: 'WEAPON_URBANRBFKNIFE', label: 'Coltello Farfalla Mimetico Urbano', image: 'weapon_urbanrbfknife.png' },
  { id: 'WEAPON_COLBATON', label: 'Sfollagente', image: 'weapon_colbaton.png' },
  { id: 'WEAPON_PETROLCAN', label: 'Jerry Can', image: 'weapon_petrolcan.png' },
  { id: 'WEAPON_GADGETPISTOL', label: 'Perico Pistol', image: 'weapon_gadgetpistol.png' },
  { id: 'WEAPON_PIPEBOMB', label: 'Pipe Bomb', image: 'weapon_pipebomb.png' },
  { id: 'WEAPON_PISTOL', label: 'Pistol', image: 'weapon_pistol.png' },
  { id: 'WEAPON_PISTOL50', label: 'Pistol .50', image: 'weapon_pistol50.png' },
  { id: 'WEAPON_PISTOL_MK2', label: 'Pistol MK2', image: 'weapon_pistol_mk2.png' },
  { id: 'WEAPON_POOLCUE', label: 'Pool Cue', image: 'weapon_poolcue.png' },
  { id: 'WEAPON_CANDYCANE', label: 'Candy Cane', image: 'weapon_candycane.png' },
  { id: 'WEAPON_PROXMINE', label: 'Proximity Mine', image: 'weapon_proxmine.png' },
  { id: 'WEAPON_PUMPSHOTGUN', label: 'Pump Shotgun', image: 'weapon_pumpshotgun.png' },
  { id: 'WEAPON_PUMPSHOTGUN_MK2', label: 'Pump Shotgun MK2', image: 'weapon_pumpshotgun_mk2.png' },
  { id: 'WEAPON_RAILGUN', label: 'Railgun', image: 'weapon_railgun.png' },
  { id: 'WEAPON_RAILGUNXM3', label: 'Railgun XM3', image: 'weapon_railgunxm3.png' },
  { id: 'WEAPON_RAYCARBINE', label: 'Unholy Hellbringer', image: 'weapon_raycarbine.png' },
  { id: 'WEAPON_RAYPISTOL', label: 'Up-n-Atomizer', image: 'weapon_raypistol.png' },
  { id: 'WEAPON_REVOLVER', label: 'Revolver', image: 'weapon_revolver.png' },
  { id: 'WEAPON_REVOLVER_MK2', label: 'Revolver MK2', image: 'weapon_revolver_mk2.png' },
  { id: 'WEAPON_RPG', label: 'RPG', image: 'weapon_rpg.png' },
  { id: 'WEAPON_SAWNOFFSHOTGUN', label: 'Sawn Off Shotgun', image: 'weapon_sawnoffshotgun.png' },
  { id: 'WEAPON_SMG', label: 'SMG', image: 'weapon_smg.png' },
  { id: 'WEAPON_SMG_MK2', label: 'SMG Mk2', image: 'weapon_smg_mk2.png' },
  { id: 'WEAPON_SMOKEGRENADE', label: 'Smoke Grenade', image: 'weapon_smokegrenade.png' },
  { id: 'WEAPON_SNIPERRIFLE', label: 'Sniper Rifle', image: 'weapon_sniperrifle.png' },
  { id: 'WEAPON_SNOWBALL', label: 'Snow Ball', image: 'weapon_snowball.png' },
  { id: 'WEAPON_SNSPISTOL', label: 'SNS Pistol', image: 'weapon_snspistol.png' },
  { id: 'WEAPON_SNSPISTOL_MK2', label: 'SNS Pistol MK2', image: 'weapon_snspistol_mk2.png' },
  { id: 'WEAPON_SPECIALCARBINE', label: 'Special Carbine', image: 'weapon_specialcarbine.png' },
  { id: 'WEAPON_SPECIALCARBINE_MK2', label: 'Special Carbine MK2', image: 'weapon_specialcarbine_mk2.png' },
  { id: 'WEAPON_STICKYBOMB', label: 'Sticky Bomb', image: 'weapon_stickybomb.png' },
  { id: 'WEAPON_FLASHBANG', label: 'Flashbang', image: 'weapon_flashbang.png' },
  { id: 'WEAPON_STONE_HATCHET', label: 'Stone Hatchet', image: 'weapon_stone_hatchet.png' },
  { id: 'WEAPON_STUNGUN', label: 'Tazer', image: 'weapon_stungun.png' },
  { id: 'WEAPON_AUTOSHOTGUN', label: 'Sweeper Shotgun', image: 'weapon_autoshotgun.png' },
  { id: 'WEAPON_SWITCHBLADE', label: 'Switchblade', image: 'weapon_switchblade.png' },
  { id: 'WEAPON_VINTAGEPISTOL', label: 'Vintage Pistol', image: 'weapon_vintagepistol.png' },
  { id: 'WEAPON_RAYMINIGUN', label: 'Widowmaker', image: 'weapon_rayminigun.png' },
  { id: 'WEAPON_WRENCH', label: 'Wrench', image: 'weapon_wrench.png' },
  { id: 'WEAPON_PRECISIONRIFLE', label: 'Precision Rifle', image: 'weapon_precisionrifle.png' },
  { id: 'WEAPON_TACTICALRIFLE', label: 'Tactical Rifle', image: 'weapon_tacticalrifle.png' },
  { id: 'WEAPON_TEARGAS', label: 'Tear Gas', image: 'weapon_teargas.png' },
  { id: 'WEAPON_DD11_B', label: 'DDM4V7 11.5 - Black', image: 'dd11_b.png' },
  { id: 'WEAPON_DD11_OD', label: 'DDM4V7 11.5 - OD', image: 'dd11_od.png' },
  { id: 'WEAPON_DD11_C', label: 'DDM4V7 11.5 - Coyote', image: 'dd11_c.png' },
  { id: 'WEAPON_DD14_B', label: 'DDM4V7 14.5 - Black', image: 'dd14_b.png' },
  { id: 'WEAPON_DD14_OD', label: 'DDM4V7 14.5 - OD', image: 'dd14_od.png' },
  { id: 'WEAPON_DD14_C', label: 'DDM4V7 14.5 - Coyote', image: 'dd14_c.png' },
  { id: 'WEAPON_DD16_B', label: 'DDM4V7 16 - Black', image: 'dd16_b.png' },
  { id: 'WEAPON_DD16_OD', label: 'DDM4V7 16 - OD', image: 'dd16_od.png' },
  { id: 'WEAPON_DD16_C', label: 'DDM4V7 16 - Coyote', image: 'dd16_c.png' },
];
